#!/bin/bash
# WatchDell Setup Script

echo "🎉 WatchDell - Complete Setup Guide 🎉"
echo "======================================="
echo ""

echo "📝 Step 1: Backend Setup"
echo "------------------------"
echo ""
echo "cd backend"
echo "npm install"
echo ""
echo "Then create .env file with:"
echo "DB_HOST=localhost"
echo "DB_USER=root"
echo "DB_PASSWORD="
echo "DB_NAME=watchdell_db"
echo "PORT=5000"
echo "JWT_SECRET=your_secret_key"
echo "ADMIN_SECRET=admin_key"
echo "CORS_ORIGIN=http://localhost:5173"
echo ""

echo "📝 Step 2: Create Database"
echo "--------------------------"
echo "mysql -u root"
echo "CREATE DATABASE watchdell_db;"
echo "EXIT;"
echo ""

echo "📝 Step 3: Start Backend"
echo "------------------------"
echo "cd backend"
echo "npm run dev"
echo ""
echo "✅ Server running at http://localhost:5000"
echo ""

echo "📝 Step 4: Frontend Setup (New Terminal)"
echo "------------------------------------------"
echo "cd frontend"
echo "npm install"
echo ""

echo "📝 Step 5: Start Frontend"
echo "------------------------"
echo "cd frontend"
echo "npm run dev"
echo ""
echo "✅ Frontend running at http://localhost:5173"
echo ""

echo "📝 Step 6: Test Authentication"
echo "------------------------------"
echo ""
echo "1. Go to http://localhost:5173/register"
echo "2. Fill the registration form"
echo "3. See success toast notification"
echo "4. User name appears in navbar"
echo "5. Go to login page"
echo "6. Login with your credentials"
echo "7. See success toast"
echo "8. Click logout"
echo "9. See logout toast"
echo ""

echo "✅ Setup Complete! 🚀"
